apiVersion: v1
kind: Service
metadata:
  name: wallet-system-service
  labels:
    run: wallet-system
spec:
  selector:
    app: wallet-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
